const $=id=>document.getElementById(id);
let sb=null,user=null,profile=null,org=null,myMembership=null;
let members=[],trucks=[],loads=[],issues=[],tasks=[],cases=[],learning=[],activity=[];
let currentPanel='dashboard';
const money=n=>'$'+Number(n||0).toLocaleString(undefined,{maximumFractionDigits:0});
const esc=s=>String(s??'').replace(/[&<>'"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[c]));
const fmt=d=>d?new Date(d).toLocaleString(): '—';
const roleLabel=r=>r==='admin'?'👑 Admin':r==='trainer'?'🎓 Trainer':'🚛 Dispatcher';
const toast=(msg)=>{const el=$('toast');el.textContent=msg;el.classList.add('show');clearTimeout(toast.t);toast.t=setTimeout(()=>el.classList.remove('show'),2600)};
function setSync(text){$('syncStatus').textContent=text}

function setupTheme(){const saved=localStorage.getItem('dispatchos.theme')||'midnight';document.documentElement.dataset.theme=saved;$('paletteSelect').value=saved;$('paletteSelect').addEventListener('change',e=>{document.documentElement.dataset.theme=e.target.value;localStorage.setItem('dispatchos.theme',e.target.value)})}

function setupUI(){
 document.querySelectorAll('.auth-tab').forEach(b=>b.addEventListener('click',()=>{document.querySelectorAll('.auth-tab').forEach(x=>x.classList.remove('active'));document.querySelectorAll('.auth-form').forEach(x=>x.classList.remove('active'));b.classList.add('active');$(b.dataset.auth+'Form').classList.add('active')}));
 document.querySelectorAll('[data-toggle]').forEach(b=>b.addEventListener('click',()=>$(b.dataset.toggle).classList.toggle('hidden')));
 document.querySelectorAll('.nav-btn').forEach(b=>b.addEventListener('click',()=>showPanel(b.dataset.panel)));
 document.querySelectorAll('.jump').forEach(b=>b.addEventListener('click',()=>showPanel(b.dataset.jump)));
 $('refreshBtn').addEventListener('click',loadWorkspaceData);$('logoutBtn').addEventListener('click',logout);$('gateLogout').addEventListener('click',logout);
 $('copyCode').addEventListener('click',async()=>{try{await navigator.clipboard.writeText(org.invite_code);toast('Team code copied')}catch{toast('Team code: '+org.invite_code)}});
}
function showPanel(id){currentPanel=id;document.querySelectorAll('.nav-btn').forEach(b=>b.classList.toggle('active',b.dataset.panel===id));document.querySelectorAll('.panel').forEach(p=>p.classList.toggle('active-panel',p.id===id));const titles={dashboard:['LIVE OPERATIONS','Command Dashboard'],fleet:['SHARED FLEET','Fleet Control'],loads:['LOAD OPERATIONS','Load Desk'],issues:['SERVICE RECOVERY','Issue Desk'],tasks:['PRIVATE WORKSPACE','My Tasks'],cases:['KNOWLEDGE SYSTEM','Case Library'],learning:['SKILL DEVELOPMENT','Learning Center'],team:['COMPANY','Team Members'],admin:['ADMIN ONLY','Admin Control Center'],activity:['AUDIT TRAIL','Workspace Activity']};$('pageEyebrow').textContent=titles[id][0];$('pageTitle').textContent=titles[id][1]}

async function init(){setupTheme();setupUI();const url=window.DISPATCHOS_SUPABASE_URL,key=window.DISPATCHOS_SUPABASE_ANON_KEY;if(!url||!key||url.includes('PASTE_')||key.includes('PASTE_')||!window.supabase){$('setupWarning').classList.remove('hidden');return}sb=window.supabase.createClient(url,key);const {data:{session}}=await sb.auth.getSession();if(session?.user)await afterLogin(session.user);sb.auth.onAuthStateChange(async(event,session)=>{if(event==='SIGNED_IN'&&session?.user&&session.user.id!==user?.id)await afterLogin(session.user);if(event==='SIGNED_OUT')showAuth()})}
async function afterLogin(u){user=u;setSync('☁️ Connected');await ensureProfile();const membership=await getMembership();if(!membership){$('authScreen').classList.add('hidden');$('workspaceGate').classList.remove('hidden');$('app').classList.add('hidden');return}myMembership=membership;await loadOrg();showApp();await loadWorkspaceData()}
function showAuth(){$('authScreen').classList.remove('hidden');$('workspaceGate').classList.add('hidden');$('app').classList.add('hidden');user=null;org=null;myMembership=null}
async function ensureProfile(){let {data}=await sb.from('profiles').select('*').eq('id',user.id).maybeSingle();if(!data){await new Promise(r=>setTimeout(r,500));({data}=await sb.from('profiles').select('*').eq('id',user.id).maybeSingle())}profile=data||{display_name:user.user_metadata?.display_name||user.email.split('@')[0],xp:0,shift_active:false}}
async function getMembership(){const {data,error}=await sb.from('organization_members').select('*').eq('user_id',user.id).eq('status','active').limit(1).maybeSingle();if(error)console.error(error);return data}
async function loadOrg(){const {data,error}=await sb.from('organizations').select('*').eq('id',myMembership.org_id).single();if(error)throw error;org=data}
function showApp(){$('authScreen').classList.add('hidden');$('workspaceGate').classList.add('hidden');$('app').classList.remove('hidden');$('orgNameDisplay').textContent=org.name;$('userName').textContent=profile.display_name;$('userRole').textContent=roleLabel(myMembership.role);$('userAvatar').textContent=(profile.display_name||'D')[0].toUpperCase();$('teamCode').textContent=org.invite_code;document.querySelectorAll('.admin-only').forEach(el=>el.classList.toggle('hidden',myMembership.role!=='admin'));document.querySelectorAll('.admin-dispatcher').forEach(el=>el.classList.toggle('hidden',!['admin','dispatcher'].includes(myMembership.role)));renderShift()}

$('loginForm').addEventListener('submit',async e=>{e.preventDefault();$('authMessage').textContent='Signing in…';const {error}=await sb.auth.signInWithPassword({email:$('loginEmail').value.trim(),password:$('loginPassword').value});$('authMessage').textContent=error?'❌ '+error.message:'✅ Signed in'})
$('signupForm').addEventListener('submit',async e=>{e.preventDefault();$('authMessage').textContent='Creating account…';const {data,error}=await sb.auth.signUp({email:$('signupEmail').value.trim(),password:$('signupPassword').value,options:{data:{display_name:$('signupName').value.trim()}}});if(error){$('authMessage').textContent='❌ '+error.message;return}$('authMessage').textContent=data.session?'✅ Account created.':'📧 Account created. Confirm your email, then log in.'})
$('createOrgForm').addEventListener('submit',async e=>{e.preventDefault();const {data,error}=await sb.rpc('create_organization',{p_name:$('orgName').value.trim()});if(error)return toast('❌ '+error.message);myMembership=await getMembership();await loadOrg();showApp();await loadWorkspaceData();toast('👑 Workspace created')})
$('joinOrgForm').addEventListener('submit',async e=>{e.preventDefault();const {error}=await sb.rpc('join_organization',{p_invite_code:$('joinCode').value.trim()});if(error)return toast('❌ '+error.message);myMembership=await getMembership();await loadOrg();showApp();await loadWorkspaceData();toast('🚛 Joined '+org.name)})
async function logout(){await sb.auth.signOut()}

async function loadWorkspaceData(){if(!org)return;setSync('☁️ Syncing…');const oid=org.id;const [m,t,l,i,ta,c,le,a,p]=await Promise.all([
 sb.from('organization_members').select('org_id,user_id,role,status,joined_at,profiles(display_name,xp,shift_active,last_seen)').eq('org_id',oid),
 sb.from('trucks').select('*').eq('org_id',oid).order('created_at',{ascending:false}),
 sb.from('loads').select('*,trucks(truck_no)').eq('org_id',oid).order('created_at',{ascending:false}),
 sb.from('issues').select('*,trucks(truck_no)').eq('org_id',oid).order('created_at',{ascending:false}),
 sb.from('tasks').select('*').eq('org_id',oid).order('created_at',{ascending:false}),
 sb.from('cases').select('*').eq('org_id',oid).order('created_at',{ascending:false}),
 sb.from('learning_notes').select('*').eq('org_id',oid).order('created_at',{ascending:false}),
 sb.from('activity_logs').select('*,profiles(display_name)').eq('org_id',oid).order('created_at',{ascending:false}).limit(100),
 sb.from('profiles').select('*').eq('id',user.id).single()
 ]);[m,t,l,i,ta,c,le,a].forEach(x=>{if(x.error)console.error(x.error)});members=m.data||[];trucks=t.data||[];loads=l.data||[];issues=i.data||[];tasks=ta.data||[];cases=c.data||[];learning=le.data||[];activity=a.data||[];profile=p.data||profile;populateSelects();renderAll();setSync('☁️ Synced')}
function memberName(uid){return members.find(m=>m.user_id===uid)?.profiles?.display_name||'Unassigned'}
function activeMembers(){return members.filter(m=>m.status==='active')}
function populateSelects(){const opts='<option value="">Unassigned</option>'+activeMembers().map(m=>`<option value="${m.user_id}">${esc(m.profiles?.display_name||'Member')} — ${esc(m.role)}</option>`).join('');['truckAssigned','loadAssigned','issueAssigned'].forEach(id=>$(id).innerHTML=opts);$('loadTruck').innerHTML='<option value="">Choose truck</option>'+trucks.map(t=>`<option value="${t.id}">${esc(t.truck_no)} — ${esc(t.driver_name)}</option>`).join('');$('issueTruck').innerHTML='<option value="">None</option>'+trucks.map(t=>`<option value="${t.id}">${esc(t.truck_no)}</option>`).join('')}
async function logAction(action,type,id,details){await sb.from('activity_logs').insert({org_id:org.id,user_id:user.id,action,entity_type:type,entity_id:id?String(id):null,details})}
async function gainXP(n){profile.xp=Number(profile.xp||0)+n;await sb.from('profiles').update({xp:profile.xp,last_seen:new Date().toISOString()}).eq('id',user.id)}

$('shiftBtn').addEventListener('click',async()=>{profile.shift_active=!profile.shift_active;await sb.from('profiles').update({shift_active:profile.shift_active,last_seen:new Date().toISOString()}).eq('id',user.id);await logAction(profile.shift_active?'Started shift':'Ended shift','profile',user.id,null);renderShift();renderDashboard()})
function renderShift(){$('shiftBtn').textContent=profile?.shift_active?'🔴 End Shift':'🟢 Start Shift'}

$('truckForm').addEventListener('submit',async e=>{e.preventDefault();const payload={org_id:org.id,truck_no:$('truckNo').value.trim(),driver_name:$('truckDriver').value.trim(),equipment:$('truckEquipment').value,driver_type:$('driverType').value,current_location:$('truckLocation').value.trim(),status:$('truckStatus').value,assigned_to:$('truckAssigned').value||null,daily_target:Number($('truckTarget').value||0),created_by:user.id};const {data,error}=await sb.from('trucks').insert(payload).select().single();if(error)return toast('❌ '+error.message);await gainXP(5);await logAction('Added truck','truck',data.id,payload.truck_no);e.target.reset();$('truckFormCard').classList.add('hidden');await loadWorkspaceData();toast('🚚 Truck added')})

$('loadForm').addEventListener('submit',async e=>{e.preventDefault();const payload={org_id:org.id,truck_id:$('loadTruck').value||null,broker:$('loadBroker').value.trim(),rate:Number($('loadRate').value||0),source:$('loadSource').value,origin:$('loadOrigin').value.trim(),destination:$('loadDestination').value.trim(),loaded_miles:Number($('loadMiles').value||0),deadhead_miles:Number($('loadDeadhead').value||0),pickup_at:$('pickupAt').value?new Date($('pickupAt').value).toISOString():null,delivery_at:$('deliveryAt').value?new Date($('deliveryAt').value).toISOString():null,reference_no:$('loadRef').value.trim(),assigned_to:$('loadAssigned').value||user.id,status:$('loadStatus').value,notes:$('loadNotes').value.trim(),created_by:user.id};const {data,error}=await sb.from('loads').insert(payload).select().single();if(error)return toast('❌ '+error.message);await gainXP(10);await logAction('Booked load','load',data.id,`${payload.origin} → ${payload.destination} · ${money(payload.rate)}`);e.target.reset();$('loadFormCard').classList.add('hidden');await loadWorkspaceData();toast('📦 Load saved')})

$('issueForm').addEventListener('submit',async e=>{e.preventDefault();const payload={org_id:org.id,title:$('issueTitle').value.trim(),issue_type:$('issueType').value,priority:$('issuePriority').value,details:$('issueDetails').value.trim(),next_action:$('issueNext').value.trim(),truck_id:$('issueTruck').value||null,assigned_to:$('issueAssigned').value||user.id,created_by:user.id};const {data,error}=await sb.from('issues').insert(payload).select().single();if(error)return toast('❌ '+error.message);await logAction('Opened issue','issue',data.id,payload.title);e.target.reset();$('issueFormCard').classList.add('hidden');await loadWorkspaceData();toast('🚨 Issue opened')})

async function addTask(title,category='Dispatch',priority='Medium',due=null,notes=''){const {data,error}=await sb.from('tasks').insert({org_id:org.id,user_id:user.id,title,category,priority,due_date:due||null,notes}).select().single();if(error)return toast('❌ '+error.message);await logAction('Added task','task',data.id,title);await loadWorkspaceData()}
$('quickTaskForm').addEventListener('submit',async e=>{e.preventDefault();const v=$('quickTask').value.trim();if(!v)return;await addTask(v);$('quickTask').value=''})
$('taskForm').addEventListener('submit',async e=>{e.preventDefault();await addTask($('taskTitle').value.trim(),$('taskCategory').value,$('taskPriority').value,$('taskDue').value,$('taskNotes').value.trim());e.target.reset();$('taskFormCard').classList.add('hidden')})

$('caseForm').addEventListener('submit',async e=>{e.preventDefault();const payload={org_id:org.id,user_id:user.id,problem:$('caseProblem').value.trim(),category:$('caseCategory').value.trim(),solution:$('caseSolution').value.trim(),lesson:$('caseLesson').value.trim(),tags:$('caseTags').value.trim(),visibility:$('caseVisibility').value};const {data,error}=await sb.from('cases').insert(payload).select().single();if(error)return toast('❌ '+error.message);await gainXP(20);await logAction('Saved case','case',data.id,payload.problem);e.target.reset();$('caseFormCard').classList.add('hidden');await loadWorkspaceData();toast('🧠 Case saved')})
$('caseSearch').addEventListener('input',renderCases);$('caseScope').addEventListener('change',renderCases);

$('learningForm').addEventListener('submit',async e=>{e.preventDefault();const payload={org_id:org.id,user_id:user.id,topic:$('learnTopic').value.trim(),source:$('learnSource').value.trim(),note:$('learnNote').value.trim(),question:$('learnQuestion').value.trim()};const {data,error}=await sb.from('learning_notes').insert(payload).select().single();if(error)return toast('❌ '+error.message);await gainXP(15);await logAction('Saved learning note','learning',data.id,payload.topic);e.target.reset();$('learningFormCard').classList.add('hidden');await loadWorkspaceData();toast('🎓 Learning saved')})

function renderAll(){renderDashboard();renderFleet();renderLoads();renderIssues();renderTasks();renderCases();renderLearning();renderTeam();renderActivity();renderAdmin();renderShift()}
function renderDashboard(){const activeLoads=loads.filter(l=>!['Delivered','Cancelled'].includes(l.status)),gross=loads.reduce((s,l)=>s+Number(l.rate||0),0),miles=loads.reduce((s,l)=>s+Number(l.loaded_miles||0),0),open=issues.filter(i=>!i.solved),mine=tasks.filter(t=>t.user_id===user.id),assigned=trucks.filter(t=>t.assigned_to===user.id);$('welcomeTitle').textContent=`${profile.shift_active?'Shift is live':'Ready to dispatch'}, ${profile.display_name}?`;$('xpValue').textContent=profile.xp||0;const xp=Number(profile.xp||0);$('levelText').textContent=xp>=1000?'Operations Commander':xp>=500?'Fleet Controller':xp>=250?'Senior Dispatcher':xp>=100?'Dispatcher Specialist':'Rookie Dispatcher';$('statTrucks').textContent=trucks.length;$('statAssigned').textContent=`${assigned.length} assigned to you`;$('statLoads').textContent=activeLoads.length;$('statLoadGross').textContent=`${money(activeLoads.reduce((s,l)=>s+Number(l.rate||0),0))} active gross`;$('statGross').textContent=money(gross);$('statRpm').textContent=`${miles?'$'+(gross/miles).toFixed(2):'$0.00'} avg RPM`;$('statIssues').textContent=open.length;$('statCritical').textContent=`${open.filter(i=>i.priority==='Critical').length} critical`;$('taskDone').textContent=mine.filter(t=>t.done).length;$('taskTotal').textContent=mine.length;$('dashboardTasks').innerHTML=mine.slice(0,6).map(t=>taskHtml(t,true)).join('')||'<div class="item meta">No tasks yet.</div>';bindTaskButtons($('dashboardTasks'));const uncover=trucks.filter(t=>t.status==='Available').length;const critical=open.filter(i=>i.priority==='Critical').length;const overdue=mine.filter(t=>!t.done&&t.due_date&&t.due_date<new Date().toISOString().slice(0,10)).length;$('attentionRadar').innerHTML=[['🚚 Available Trucks',uncover,'Need freight'],['🔴 Critical Issues',critical,'Handle first'],['⏰ Overdue Tasks',overdue,'Personal follow-up'],['🧠 Knowledge',cases.length+learning.length,'Cases + learning']].map(x=>`<div class="radar"><span class="muted">${x[0]}</span><strong>${x[1]}</strong><small class="muted">${x[2]}</small></div>`).join('');$('dashboardLoads').innerHTML=loadTable(activeLoads.slice(0,8),false)}
function statusBadge(s){const cls=['Available','Delivered','Covered'].includes(s)?'good':['Breakdown','Cancelled','Critical'].includes(s)?'danger':'warn';return `<span class="badge ${cls}">${esc(s)}</span>`}
function renderFleet(){$('fleetGrid').innerHTML=trucks.map(t=>`<article class="card truck-card"><div class="top"><div><p class="eyebrow">TRUCK ${esc(t.truck_no)}</p><h3>${esc(t.driver_name)}</h3><div class="meta">${esc(t.equipment)} · ${esc(t.driver_type)}</div></div>${statusBadge(t.status)}</div><div class="metric-row"><div class="metric"><small>📍 Location</small><strong>${esc(t.current_location||'Not set')}</strong></div><div class="metric"><small>👤 Dispatcher</small><strong>${esc(memberName(t.assigned_to))}</strong></div><div class="metric"><small>🎯 Daily target</small><strong>${money(t.daily_target)}</strong></div><div class="metric"><small>Updated</small><strong>${fmt(t.updated_at).split(',')[0]}</strong></div></div></article>`).join('')||'<div class="card muted">No trucks yet.</div>'}
function rpm(l){return Number(l.loaded_miles)>0?(Number(l.rate)/Number(l.loaded_miles)).toFixed(2):'0.00'}function allIn(l){const m=Number(l.loaded_miles||0)+Number(l.deadhead_miles||0);return m>0?(Number(l.rate)/m).toFixed(2):'0.00'}
function loadTable(list,actions=true){return `<table class="data-table"><thead><tr><th>Truck</th><th>Lane</th><th>Broker</th><th>Rate</th><th>RPM</th><th>All-in</th><th>Dispatcher</th><th>Status</th>${actions?'<th>Action</th>':''}</tr></thead><tbody>${list.map(l=>`<tr><td>${esc(l.trucks?.truck_no||'—')}</td><td><b>${esc(l.origin)}</b><br><span class="meta">→ ${esc(l.destination)}</span></td><td>${esc(l.broker)}<br><span class="meta">${esc(l.source)}</span></td><td>${money(l.rate)}</td><td>$${rpm(l)}</td><td>$${allIn(l)}</td><td>${esc(memberName(l.assigned_to))}</td><td>${statusBadge(l.status)}</td>${actions?`<td><select class="load-status" data-id="${l.id}"><option>Booked</option><option>At Pickup</option><option>In Transit</option><option>At Delivery</option><option>Delivered</option><option>Cancelled</option></select></td>`:''}</tr>`).join('')}</tbody></table>`}
function renderLoads(){$('loadsTable').innerHTML=loadTable(loads,true);document.querySelectorAll('.load-status').forEach(sel=>{const l=loads.find(x=>x.id===sel.dataset.id);sel.value=l.status;sel.disabled=!['admin','dispatcher'].includes(myMembership.role);sel.addEventListener('change',async()=>{const was=l.status;l.status=sel.value;await sb.from('loads').update({status:l.status,updated_at:new Date().toISOString()}).eq('id',l.id);if(l.status==='Delivered'&&was!=='Delivered')await gainXP(20);await logAction('Updated load status','load',l.id,`${was} → ${l.status}`);await loadWorkspaceData()})})}
function renderIssues(){$('issuesList').innerHTML=issues.map(i=>`<article class="item issue-card ${i.priority.toLowerCase()}"><div class="item-row"><div><h3 style="margin:0">${i.solved?'✅':'🚨'} ${esc(i.title)}</h3><div class="meta">${esc(i.issue_type)} · ${esc(i.priority)} · Truck ${esc(i.trucks?.truck_no||'—')} · Assigned: ${esc(memberName(i.assigned_to))}</div></div>${statusBadge(i.solved?'Resolved':i.priority)}</div><p>${esc(i.details)}</p>${i.next_action?`<div class="notice"><b>➡️ Next action:</b> ${esc(i.next_action)}</div>`:''}<div class="issue-actions"><button class="small-btn issue-toggle" data-id="${i.id}">${i.solved?'↩️ Reopen':'✅ Resolve'}</button><button class="small-btn issue-case" data-id="${i.id}">🧠 Save as Case</button></div></article>`).join('')||'<div class="card muted">No issues recorded.</div>';document.querySelectorAll('.issue-toggle').forEach(b=>b.addEventListener('click',async()=>{const i=issues.find(x=>x.id===b.dataset.id);const solved=!i.solved;await sb.from('issues').update({solved,resolved_at:solved?new Date().toISOString():null,updated_at:new Date().toISOString()}).eq('id',i.id);if(solved)await gainXP(20);await logAction(solved?'Resolved issue':'Reopened issue','issue',i.id,i.title);await loadWorkspaceData()}));document.querySelectorAll('.issue-case').forEach(b=>b.addEventListener('click',()=>{const i=issues.find(x=>x.id===b.dataset.id);showPanel('cases');$('caseProblem').value=i.title;$('caseCategory').value=i.issue_type;$('caseSolution').value=i.details;$('caseLesson').value=i.next_action||'';$('caseVisibility').value='company';$('caseFormCard').classList.remove('hidden')}))}
function taskHtml(t,compact=false){return `<div class="item item-row"><label style="display:flex;grid-template-columns:auto 1fr;align-items:center;gap:10px;margin:0;flex:1"><input class="task-check" data-id="${t.id}" type="checkbox" style="width:auto" ${t.done?'checked':''}><span><b ${t.done?'style="text-decoration:line-through;opacity:.55"':''}>${esc(t.title)}</b>${compact?'':`<div class="meta">${esc(t.category||'Task')} · ${esc(t.priority||'Medium')}${t.due_date?' · Due '+esc(t.due_date):''}</div>`}</span></label>${compact?'':`<button class="small-btn task-delete" data-id="${t.id}">🗑️</button>`}</div>`}
function bindTaskButtons(root=document){root.querySelectorAll('.task-check').forEach(c=>c.addEventListener('change',async()=>{const t=tasks.find(x=>x.id===c.dataset.id);await sb.from('tasks').update({done:c.checked,updated_at:new Date().toISOString()}).eq('id',t.id);if(c.checked)await gainXP(10);await logAction(c.checked?'Completed task':'Reopened task','task',t.id,t.title);await loadWorkspaceData()}));root.querySelectorAll('.task-delete').forEach(b=>b.addEventListener('click',async()=>{await sb.from('tasks').delete().eq('id',b.dataset.id);await loadWorkspaceData()}))}
function renderTasks(){const mine=tasks.filter(t=>t.user_id===user.id);$('tasksList').innerHTML=mine.map(t=>taskHtml(t)).join('')||'<div class="card muted">No personal tasks yet.</div>';bindTaskButtons($('tasksList'))}
function renderCases(){const q=($('caseSearch').value||'').toLowerCase(),scope=$('caseScope').value;let list=cases.filter(c=>(scope==='all'||c.visibility===scope));list=list.filter(c=>(`${c.problem} ${c.category} ${c.solution} ${c.lesson} ${c.tags}`).toLowerCase().includes(q));$('casesList').innerHTML=list.map(c=>`<article class="item case-card ${c.visibility}"><div class="item-row"><div><h3 style="margin:0">🧩 ${esc(c.problem)}</h3><div class="meta">${c.visibility==='company'?'🏢 Company':'🔒 Personal'} · ${esc(c.category||'General')} · by ${esc(memberName(c.user_id))}</div></div><span class="badge ${c.visibility==='company'?'good':'warn'}">${esc(c.visibility)}</span></div><p><b>✅ Solution:</b> ${esc(c.solution)}</p><p><b>💡 Next time:</b> ${esc(c.lesson||'—')}</p>${c.tags?`<div class="meta">🏷 ${esc(c.tags)}</div>`:''}</article>`).join('')||'<div class="card muted">No matching cases.</div>'}
function renderLearning(){const list=learning.filter(l=>l.user_id===user.id);$('learningList').innerHTML=list.map(l=>`<article class="item"><h3 style="margin:0">🎓 ${esc(l.topic)}</h3><div class="meta">${esc(l.source||'Personal learning')} · ${fmt(l.created_at)}</div><p>📘 ${esc(l.note)}</p><p>${l.question?'❓ '+esc(l.question):'✅ No open question.'}</p></article>`).join('')||'<div class="card muted">No learning notes yet.</div>'}
function renderTeam(){$('teamList').innerHTML=activeMembers().map(m=>`<article class="card member-card"><div class="top"><div><p class="eyebrow">TEAM MEMBER</p><h3>${esc(m.profiles?.display_name||'Member')}</h3><div class="meta">${roleLabel(m.role)}</div></div><div class="avatar">${esc((m.profiles?.display_name||'M')[0].toUpperCase())}</div></div><div class="metric-row"><div class="metric"><small>⭐ XP</small><strong>${m.profiles?.xp||0}</strong></div><div class="metric"><small>Shift</small><strong>${m.profiles?.shift_active?'🟢 Live':'⚪ Off'}</strong></div></div>${myMembership.role==='admin'&&m.user_id!==user.id?`<label style="margin-top:12px">Role<select class="role-select" data-user="${m.user_id}"><option value="dispatcher">Dispatcher</option><option value="trainer">Trainer</option><option value="admin">Admin</option></select></label>`:''}</article>`).join('');document.querySelectorAll('.role-select').forEach(s=>{const m=members.find(x=>x.user_id===s.dataset.user);s.value=m.role;s.addEventListener('change',async()=>{const {error}=await sb.from('organization_members').update({role:s.value}).eq('org_id',org.id).eq('user_id',m.user_id);if(error)return toast('❌ '+error.message);await logAction('Changed member role','member',m.user_id,`${m.role} → ${s.value}`);await loadWorkspaceData();toast('Role updated')})})}
function renderActivity(){const html=activity.map(a=>`<div class="item activity-row"><div class="activity-icon">${a.entity_type==='load'?'📦':a.entity_type==='truck'?'🚚':a.entity_type==='issue'?'🚨':a.entity_type==='task'?'🎯':a.entity_type==='case'?'🧠':a.entity_type==='learning'?'🎓':'📜'}</div><div><b>${esc(a.profiles?.display_name||'Member')} · ${esc(a.action)}</b><div class="meta">${esc(a.details||a.entity_type||'')}</div></div><div class="meta">${fmt(a.created_at)}</div></div>`).join('')||'<div class="card muted">No activity yet.</div>';$('activityList').innerHTML=html;$('adminActivity').innerHTML=activity.slice(0,12).map(a=>`<div class="item"><b>${esc(a.profiles?.display_name||'Member')}</b> · ${esc(a.action)}<div class="meta">${esc(a.details||'')} · ${fmt(a.created_at)}</div></div>`).join('')}
function renderAdmin(){if(myMembership.role!=='admin')return;const delivered=loads.filter(l=>l.status==='Delivered').length,gross=loads.reduce((s,l)=>s+Number(l.rate||0),0),critical=issues.filter(i=>!i.solved&&i.priority==='Critical').length;$('adminMembers').textContent=activeMembers().length;$('adminGross').textContent=money(gross);$('adminDelivered').textContent=delivered;$('adminCritical').textContent=critical;const rows=activeMembers().map(m=>{const uid=m.user_id,ml=loads.filter(l=>l.assigned_to===uid),mi=issues.filter(i=>i.assigned_to===uid),mt=tasks.filter(t=>t.user_id===uid),gross=ml.reduce((s,l)=>s+Number(l.rate||0),0),miles=ml.reduce((s,l)=>s+Number(l.loaded_miles||0),0);return `<tr><td><b>${esc(m.profiles?.display_name||'Member')}</b><br><span class="meta">${roleLabel(m.role)}</span></td><td>${ml.length}</td><td>${money(gross)}</td><td>${miles?'$'+(gross/miles).toFixed(2):'$0.00'}</td><td>${mi.filter(i=>!i.solved).length}</td><td>${mt.filter(t=>t.done).length}/${mt.length}</td><td>${m.profiles?.xp||0}</td><td>${m.profiles?.shift_active?'🟢 Live':'⚪ Off'}</td></tr>`}).join('');$('adminScoreboard').innerHTML=`<table class="data-table"><thead><tr><th>Member</th><th>Loads</th><th>Gross</th><th>RPM</th><th>Open Issues</th><th>Tasks</th><th>XP</th><th>Shift</th></tr></thead><tbody>${rows}</tbody></table>`}

init();
